# Generated by Django 3.0.11 on 2020-12-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_accountstatus_user_name'),
        ('profiles', '0015_auto_20180423_0727'),
    ]

    operations = [
    ]
